In [3]:
# This program takes lists of lobbyist registration termination dates from the City of Austin's data portal and uses
# them to calculate when the lobbyists were hired and how long they remained registered to represent the same clients.

import csv, copy
import datetime

def addLobby(file, lobbyistList):
    newFile = open(file)
    newReader = csv.reader(newFile)
    newData = list(newReader)
    for row in newData[1:]:
        endDate = datetime.datetime.strptime(row[3], "%m/%d/%Y").date()
        startDate = endDate - datetime.timedelta(days=365)
        fullName = row[1] + ' ' + row[0] # merging separate first and last name fields
        lobbyistList.append([startDate, endDate, fullName, row[4], row[6], row[5]])

lobbyists = []
files = ['lobbyists2014.csv', 'lobbyists2015.csv', 'lobbyists2015-10.csv', 'lobbyists2016.csv', 'lobbyists2016-03.csv']

for file in files:
    addLobby(file, lobbyists)

In [4]:
outputFile = open('lobbyistFromCity.csv', 'w', newline='')
outputWriter = csv.writer(outputFile)
outputWriter.writerow(['Start', 'End', 'Lobbyist', 'Client', 'Industry', 'ClientAddress'])
for row in lobbyists:
    outputWriter.writerow(row)
outputFile.close()

At this point I used csvdedupe on the Client, Industry, and ClientAddress fields of lobbyistFromCity.csv, and exported lobbyistDedupe.csv. I'm not clear on whether I could have used dedupe instead of csvdedupe to keep the whole process in this notebook.

In [108]:
import csv, copy
import datetime

def addDLobby(file, lobbyistList):
    newFile = open(file)
    newReader = csv.reader(newFile)
    newData = list(newReader)
    # Watch out, I'm not bothering to bring the addresses back in
    for row in newData[1:]:
        endDate = datetime.datetime.strptime(row[2], "%Y-%m-%d").date()
        startDate = datetime.datetime.strptime(row[1], "%Y-%m-%d").date()
        lobbyistList.append([startDate, endDate, row[3], row[4], row[5], int(row[0])])

lobbyists = []
files = ['lobbyistDedupe.csv']

for file in files:
    addDLobby(file, lobbyists)

q = type(lobbyists[1][5])
print(q)

<class 'int'>

In [109]:
import re

# Cleaning client names
    
for lobbyist in lobbyists:
    lobbyist[3] = lobbyist[3].rstrip()
    # get rid of ' c\o' followed by anything to the end of the line
    lobbyist[3] = re.sub(',? (c/o|attn:|Attn:).*$', '', lobbyist[3])
    lobbyist[3] = re.sub('\,? L\.?L?\.?(C|P)\.?\,?$', '', lobbyist[3])
    lobbyist[3] = re.sub(',? I(n|m|N)(c|C)(\.|(orporated))? ?$', '', lobbyist[3])
    lobbyist[3] = re.sub(',? L(t|T)(d|D).?$', '', lobbyist[3])
    lobbyist[3] = re.sub('\, P\.?C\.?,?$', '', lobbyist[3])
    lobbyist[3] = lobbyist[3].replace("Acheive","Achieve")
    lobbyist[3] = lobbyist[3].replace('  ',' ')
    lobbyist[3] = lobbyist[3].replace(' - Austin','')
    lobbyist[3] = lobbyist[3].replace(' (Vance Elliott)','')
    lobbyist[3] = lobbyist[3].replace('2208 Lake Austin, LLC','2208 Lake Austin')
    lobbyist[3] = lobbyist[3].replace('Amini, Ashley','Ashley Amini')
    lobbyist[3] = lobbyist[3].replace('A T & T','AT&T')
    lobbyist[3] = lobbyist[3].replace('AT & T','AT&T')
    lobbyist[3] = lobbyist[3].replace('A T and T','AT&T')
    lobbyist[3] = lobbyist[3].replace('AT and T','AT&T')
    lobbyist[3] = re.sub('AT&T.*$','AT&T', lobbyist[3])
    lobbyist[3] = lobbyist[3].replace('AT& T','AT&T')
    lobbyist[3] = lobbyist[3].replace(" & ", " and ")
    lobbyist[3] = lobbyist[3].replace('Attal, Deborah and Gary','Deborah and Gary Attal')
    lobbyist[3] = lobbyist[3].replace('Austin Elm Terrace LP (Steve Beuerlein)','Austin Elm Terrace LP')
    lobbyist[3] = lobbyist[3].replace('Austin Elm Terrace, LP Burlington Ventures','Austin Elm Terrace LP')
    lobbyist[3] = lobbyist[3].replace('Autoreturn','AutoReturn')
    lobbyist[3] = lobbyist[3].replace('Behringer Harvard Terrace','Behringer Harvard')
    lobbyist[3] = lobbyist[3].replace('Blatt, Jeff','Jeff Blatt')
    lobbyist[3] = re.sub('David Booth$','David and Suzanne Booth',lobbyist[3])
    lobbyist[3] = re.sub('Booth, David and Suzanne$','David and Suzanne Booth',lobbyist[3])
    lobbyist[3] = re.sub('Booth, David$','David and Suzanne Booth',lobbyist[3])
    lobbyist[3] = lobbyist[3].replace('Booth, Suzanne Deal','David and Suzanne Booth')
    lobbyist[3] = lobbyist[3].replace('Booth and Suzanne','Booth')
    lobbyist[3] = lobbyist[3].replace('Bridges, Will','Will Bridges')
    lobbyist[3] = lobbyist[3].replace('Burris, Gene','Gene Burris')
    lobbyist[3] = lobbyist[3].replace('Browning, Karen','Karen Browning')
    lobbyist[3] = lobbyist[3].replace('Follett, Brian','Brian Follett')
    lobbyist[3] = lobbyist[3].replace('Byrne, Dan','Dan Byrne')
    lobbyist[3] = lobbyist[3].replace('Calderon, Alex and Mark','Alex and Mark Calderon')
    lobbyist[3] = lobbyist[3].replace('Alex Calderon Mark Calderon','Alex and Mark Calderon')
    lobbyist[3] = lobbyist[3].replace('Caledona Properties','Caledonia Properties')
    lobbyist[3] = lobbyist[3].replace('Capital Metropolitan Transportation Authority','Capital Metro')
    lobbyist[3] = lobbyist[3].replace('Cathcart, Mark','Mark Cathcart')
    lobbyist[3] = lobbyist[3].replace('Cavanaugh, Roy','Roy Cavanaugh')
    lobbyist[3] = lobbyist[3].replace('Castle Hill Partners','Castle Hill Management')
    lobbyist[3] = re.sub('Carollo$','Carollo Engineers', lobbyist[3])
    lobbyist[3] = lobbyist[3].replace('Fisher, Chereen','Chereen Fisher')
    lobbyist[3] = lobbyist[3].replace('Dildy, Charles S. and Bertha Magdelan Steger, Trustees','Charles S. Dildy and Bertha Magdelan Steger Dildy, Trustees')
    lobbyist[3] = lobbyist[3].replace('Dorrance, Charles','Charles Dorrance')
    lobbyist[3] = re.sub('Colina West.*$','Colina West Real Estate', lobbyist[3])
    lobbyist[3] = re.sub('Lennar.*$','Lennar Homes', lobbyist[3])
    lobbyist[3] = re.sub('Amstar.*$','Amstar Group', lobbyist[3])
    lobbyist[3] = lobbyist[3].replace('Crown Castle USA', 'Crown Castle')
    lobbyist[3] = re.sub(' Corporation$','', lobbyist[3])
    lobbyist[3] = lobbyist[3].replace('Cypress Real Estate Advisors','Cypress Realty')
    lobbyist[3] = lobbyist[3].replace('Cypress VI Reit','Cypress Realty')
    lobbyist[3] = lobbyist[3].replace('Davidson, David','David Davidson')
    lobbyist[3] = lobbyist[3].replace('DeRoeck, Walter A.','Walter A. DeRoeck')
    lobbyist[3] = lobbyist[3].replace('Development Company','Development')
    lobbyist[3] = lobbyist[3].replace('Ehrlich, Robert','Robert Ehrlich')
    lobbyist[3] = lobbyist[3].replace('English, Toria and Blake','Toria and Blake English')
    lobbyist[3] = re.sub('Eureka$','Eureka Holdings', lobbyist[3])
    lobbyist[3] = lobbyist[3].replace('Fagan, Dennis','Dennis Fagan')
    lobbyist[3] = lobbyist[3].replace('Fagan, ','Fagan ')
    lobbyist[3] = lobbyist[3].replace('George, Anthony','Anthony George')
    lobbyist[3] = re.sub('^HEB$','H-E-B', lobbyist[3])
    lobbyist[3] = lobbyist[3].replace('Hardeman, Bryan','Bryan Hardeman')
    lobbyist[3] = lobbyist[3].replace('HEB Grocery Stores','H-E-B')
    lobbyist[3] = lobbyist[3].replace('H-E-B Grocery Stores','H-E-B')
    lobbyist[3] = lobbyist[3].replace('Gerbracht Heidi','Heidi Gerbracht') 
    lobbyist[3] = lobbyist[3].replace('Highland Resources','Highland Management')
    lobbyist[3] = lobbyist[3].replace('Jackson, Glenn','Glenn Jackson')
    lobbyist[3] = lobbyist[3].replace(', Jr.',' Jr.')
    lobbyist[3] = lobbyist[3].replace('JP Morgan Chase Bank - Mail Code IL1-0930, ATTN Retail Portfolio Manager','JP Morgan Chase Bank')
    lobbyist[3] = lobbyist[3].replace('Gorence, Kenneth','Kenneth Gorence')
    lobbyist[3] = lobbyist[3].replace('Lambert, Liz','Liz Lambert')
    lobbyist[3] = lobbyist[3].replace('Laney, Terry','Terry Laney')
    lobbyist[3] = lobbyist[3].replace('Moody, Linda', 'Linda Moody') 
    lobbyist[3] = lobbyist[3].replace('Lindy Moody', 'Linda Moody')
    lobbyist[3] = lobbyist[3].replace('Multiplyer', 'Multiplier')
    lobbyist[3] = lobbyist[3].replace('Lopez, Edward','Edward Lopez')
    lobbyist[3] = re.sub('Met Center.*$', 'Met Center', lobbyist[3])
    lobbyist[3] = lobbyist[3].replace('Momin, Sohil','Sohil Momin')
    lobbyist[3] = lobbyist[3].replace('Moritz,Jim','Moritz, Jim')
    lobbyist[3] = re.sub('Properties #\d', 'Properties', lobbyist[3])
    lobbyist[3] = lobbyist[3].replace('Patel, Vijay','Vijay Patel')
    lobbyist[3] = lobbyist[3].replace('Reality Investor','Realty Investor')
    lobbyist[3] = lobbyist[3].replace('Reddehase, Eric','Eric Reddehase')
    lobbyist[3] = lobbyist[3].replace('Ross, Robert','Robert Ross')
    if lobbyist[3] == 'Redflex Guardian': lobbyists.remove(lobbyist)
    if lobbyist[3] == 'RedLeaf Highland': lobbyists.remove(lobbyist)
    lobbyist[3] = lobbyist[3].replace('Reynolds, Cary and Cynthia','Reynolds, Cary and Cynthia')
    lobbyist[3] = lobbyist[3].replace('Robert P.Wills','Robert P. Wills')
    lobbyist[3] = lobbyist[3].replace('Wills, Robert P.','Robert P. Wills')
    lobbyist[3] = lobbyist[3].replace('Scarbrough Wilson, Margaret','Margaret Scarbrough Wilson')
    lobbyist[3] = lobbyist[3].replace('Wilson, Randy','Randy Wilson')
    lobbyist[3] = lobbyist[3].replace('Sayers, Scott','Scott Sayers')
    lobbyist[3] = lobbyist[3].replace('Schmidt, Robert','Robert Schmidt')
    lobbyist[3] = re.sub('Seton$','Seton Healthcare', lobbyist[3])
    lobbyist[3] = re.sub('Seton Healthcare.*$','Seton Healthcare', lobbyist[3])
    lobbyist[3] = lobbyist[3].replace('Slover, Christopher','Christopher Slover')
    lobbyist[3] = lobbyist[3].replace('Smith, Ford Jr.','Ford Smith Jr.')
    lobbyist[3] = lobbyist[3].replace('Schoenbaum, James','James Schoenbaum')
    lobbyist[3] = lobbyist[3].replace('Greenberg, Steve','Steve Greenberg')
    lobbyist[3] = re.sub('Partners (I|II|III|IV|V|VI|VII|VIII) ', 'Partners ', lobbyist[3])
    lobbyist[3] = re.sub('Realty (I|II|III|IV|V|VI|VII|VIII) ', 'Realty ', lobbyist[3])
    lobbyist[3] = lobbyist[3].replace(' Limited Partnership','')
    lobbyist[3] = lobbyist[3].replace(' PHASE II','')
    lobbyist[3] = lobbyist[3].replace('Reynolds, Cary and Cynthia','Cary and Cynthia Reynolds')
    lobbyist[3] = lobbyist[3].replace('Samsung Austin Semiconductor','Samsung')
    lobbyist[3] = lobbyist[3].replace("St. David's Community Health Foundation Initiatives", "St. David's Foundation")
    lobbyist[3] = lobbyist[3].replace('Schneider, James','James Schneider')
    lobbyist[3] = lobbyist[3].replace('Simmons Vedder and Co.','Simmons Vedder Partners')
    lobbyist[3] = lobbyist[3].replace('Simon Properties', 'Simon Property Group')
    lobbyist[3] = lobbyist[3].replace('Spire Realty Group','Spire Realty')
    lobbyist[3] = lobbyist[3].replace('SXSW Properties','SXSW')
    lobbyist[3] = lobbyist[3].replace('Saleem Tawill','Saleem Tawill')
    lobbyist[3] = re.sub(' Corp$', '', lobbyist[3])
    lobbyist[3] = lobbyist[3].replace("St. David's Healthcare Center", "St. David's Foundation")
    lobbyist[3] = re.sub('Stratford$', 'Stratford Land', lobbyist[3])
    lobbyist[3] = lobbyist[3].replace('Snyder, Suzanne','Suzanne Snyder')
    lobbyist[3] = re.sub('Lone Star Rail$', 'Lone Star Rail', lobbyist[3])
    lobbyist[3] = re.sub('Tantallon Austin$','Tantallon Austin Hotel', lobbyist[3])
    lobbyist[3] = lobbyist[3].replace('Telvending','Televending')
    lobbyist[3] = lobbyist[3].replace('Texs Aggregates and Concrete Association','Texas Aggregates and Concrete Association')
    lobbyist[3] = lobbyist[3].replace('Theriot, Robert H.','Robert H. Theriot')
    lobbyist[3] = lobbyist[3].replace('Trinity Insurance Services','Trinity Insurance Group')
    lobbyist[3] = lobbyist[3].replace('Turner,Ben','Turner, Ben')
    lobbyist[3] = lobbyist[3].replace('Ben, Consort','Ben')
    lobbyist[3] = lobbyist[3].replace('Turner, Rob','Robert Turner')
    lobbyist[3] = lobbyist[3].replace('Naddef, Wilfred','Wilfred Naddef')
    lobbyist[3] = lobbyist[3].replace('Wiman, Sophie', 'Sophie Wiman')
    lobbyist[3] = lobbyist[3].replace('The County Line','County Line')
    lobbyist[3] = lobbyist[3].replace('University of Texas, Board of Regents', 'The University of Texas System')
    lobbyist[3] = re.sub('URSTCO$','URSTCO GP', lobbyist[3])
    lobbyist[3] = lobbyist[3].replace(' (USA)','')
    lobbyist[3] = lobbyist[3].replace('Vega, Shirley','Shirley Vega')
    lobbyist[3] = lobbyist[3].replace('Vegas Properties','Vargas Properties')
    lobbyist[3] = re.sub('Wal-Mart.*$','Wal-Mart', lobbyist[3])
    lobbyist[3] = re.sub('Walton Stacy.*$', 'Walton Stacy Partners', lobbyist[3])
    lobbyist[3] = re.sub('Western Rim Invest.*$','Western Rim Investment Advisors', lobbyist[3])
    lobbyist[3] = lobbyist[3].replace('Whitfield, Marcus','Marcus Whitfield')
    lobbyist[3] = lobbyist[3].replace("\x19","'")
    lobbyist[3] = lobbyist[3].rstrip()

In [110]:
canonClients = {}
done = []
canonClients[771] = ("Scarbrough Ventures", "Property Owner")
canonClients[766] = ("Lack and Hurley", "Property Owner")

for lobbyist in reversed(lobbyists):
    if lobbyist[5] not in canonClients:
        # print("haven't seen " + lobbyist[5] + " before.")
        canonClients[lobbyist[5]] = (lobbyist[3], lobbyist[4])
    else:
        # excluding my handcrafted list of "duplicate" sets that make no sense
        if lobbyist[5] not in (56, 68, 70, 72, 98, 106, 110, 117, 119, 121, 143, 162, 203, 299, 300, 307, 319, 362, 458, 460, 492, 675, 684, 719, 722, 727, 740, 743, 763, 817, 818) and lobbyist[3] not in ("Radec Management",):
            if lobbyist[3] != canonClients[lobbyist[5]][0] or lobbyist[4] != canonClients[lobbyist[5]][1]:
                if lobbyist[5] not in done:
                    done.append(lobbyist[5])
                    print("changing " + lobbyist[3] + " to " + str(canonClients[lobbyist[5]][0]) + " because lobbyist[5] is " + str(lobbyist[5]))
                lobbyist[3] = canonClients[lobbyist[5]][0]
                lobbyist[4] = canonClients[lobbyist[5]][1]

changing MU 13 to 1600 West 38th because lobbyist[5] is 206
changing The Brick Oven Restaurant to Bradz Salon because lobbyist[5] is 720
changing Keyes, Mary Alice to Monocoque Diversified Interests because lobbyist[5] is 317
changing Floresta Properties to Scarbrough Ventures because lobbyist[5] is 771
changing Riverside Resources to Riverside Resources Investments, Limited because lobbyist[5] is 100
changing HRI Development to Highland Management because lobbyist[5] is 705
changing URSTCO GP to URSTCO GP because lobbyist[5] is 785
changing INTCO Properties to INTCO Development of Texas because lobbyist[5] is 345
changing IBC Bank to International Bank of Commerce, Laredo, Texas because lobbyist[5] is 695
changing Real Estate Council of Austin to The Real Estate Council of Austin, Inc. because lobbyist[5] is 497
changing Workers Defense Action Fund to Workers Defense Project because lobbyist[5] is 41
changing CPF River Oaks Austin to Cornerstone Patriot Holdings because lobbyist[5] is 688
changing Met Center to Met Center because lobbyist[5] is 461
changing Jeff Blatt to Quest Tower View because lobbyist[5] is 714
changing Covered Bridge to Covered Bridge Section 8 because lobbyist[5] is 639
changing Harmony Cottages to Wagwater Partners because lobbyist[5] is 84
changing ATC Outdoor DAS to UniSite because lobbyist[5] is 335
changing Howard and Howard Attorneys, PLLC to Insurance Auto Auctions because lobbyist[5] is 420
changing Travis County Healthcare District to Central Health because lobbyist[5] is 411
changing Oxford Alliance Investments to Oxford Alliance Investments because lobbyist[5] is 334
changing 1530 Barton Springs to RDE Assets because lobbyist[5] is 598
changing 2428 Partners to A and M Option 541 because lobbyist[5] is 272
changing KB Home Central Texas Division to KB Home Lone Star because lobbyist[5] is 735
changing AT&T to AT&T because lobbyist[5] is 101
changing Reagan Signs to Reagan National Advertising because lobbyist[5] is 832
changing Stratford Land to The Stratford Company because lobbyist[5] is 564
changing Street Lights Residential to Street Lights Residential because lobbyist[5] is 265
changing 6ixth Street Austin to Pecan Street Association because lobbyist[5] is 65
changing Amstar Group to Walton Stacy Partners because lobbyist[5] is 111
changing Home Away to HomeAway because lobbyist[5] is 381
changing CRV Shoreline to Cypress Realty because lobbyist[5] is 112
changing Gerald Kucera to The Kucera Companies because lobbyist[5] is 86
changing St. David's Foundation to St. David's Foundation because lobbyist[5] is 815
changing Spire Realty to Spire Realty because lobbyist[5] is 880
changing Texas Disposal Systems to Texas Disposal Systems because lobbyist[5] is 638
changing Makar Development - Waters Edge to Makar Properties because lobbyist[5] is 175
changing REIT Management to REIT Management and Research because lobbyist[5] is 165
changing Simon Property Group to Simon Property Group because lobbyist[5] is 229
changing Pagura, Steve to Steve Pagura because lobbyist[5] is 813
changing Terrell Gates to Terrell Gates because lobbyist[5] is 125
changing Forestar Real Estate Group to Forestar Real Estate Group because lobbyist[5] is 46
changing Texas Aggregates and Concrete Association to Texas Aggregates and Concrete Association because lobbyist[5] is 737
changing El Rey Network to El Rey Network, LLC because lobbyist[5] is 522
changing Bridges on The Park Condominium Association to Bridges on The Park Condominium Association, Inc. because lobbyist[5] is 491
changing Schoenbaum, James to James Schoenbaum because lobbyist[5] is 867
changing Whatabrands to Whataburger because lobbyist[5] is 288
changing Uber Technologies, Inc to Uber Technologies because lobbyist[5] is 655
changing Redflex Traffic Systems, Inc. to Redflex Traffic Systems because lobbyist[5] is 450
changing AETNA Sign Group to Aetna Sign Group because lobbyist[5] is 816
changing Dinerstein Company to The Dinerstein Companies because lobbyist[5] is 60
changing Stratus Properties to Stratus Properties because lobbyist[5] is 523
changing Lennar Homes to Lennar Homes because lobbyist[5] is 532
changing Jim Gallegos to Gallegos, Jim because lobbyist[5] is 746
changing Lincoln Property Company to Lincoln Property Company because lobbyist[5] is 242
changing Sam Mikhail to Mikhail, Sam because lobbyist[5] is 828
changing Dr. Pejman Khosravian to Khosravian, Dr. Pejman because lobbyist[5] is 160
changing Peter Barlin to Barlin, Peter because lobbyist[5] is 480
changing David Morrison to Morrison, David because lobbyist[5] is 392
changing Schlosser Development (Rick Duggan III) to Schlosser Development because lobbyist[5] is 399
changing PPF AMLI covered Bridge Drive to PPF AMLI Covered Bridge Drive because lobbyist[5] is 465
changing MB 26 Properties to NB 26 Properties because lobbyist[5] is 464
changing Gables Residential to Gables Residential because lobbyist[5] is 107
changing Lica Pinkston to Pinkston, Lica because lobbyist[5] is 191
changing Chris Pacitti to Pacitti, Chris because lobbyist[5] is 868
changing David Middleton to Middleton, David because lobbyist[5] is 866
changing Roy Cavanaugh to Roy Cavanaugh because lobbyist[5] is 271
changing Navid Hoomanrad to Hoomanrad, Navid because lobbyist[5] is 620
changing Robinson Ranch to Robinson Ranch because lobbyist[5] is 805
changing Robbins, Stewart to Robbins, Stuart B. because lobbyist[5] is 800
changing Peter Gilcrease to Gilcrease, Peter because lobbyist[5] is 430
changing Coover, David M. Jr. to Coover and Coover because lobbyist[5] is 679
changing Nelson, Brad to Nelsen, Brad because lobbyist[5] is 291
changing The Dovetail Companies  to The Dovetail Companies because lobbyist[5] is 757
changing Michael J. McGinnis to McGinnis, Michael J. because lobbyist[5] is 331
changing Lampros Moumouris to Moumouris, Lampros because lobbyist[5] is 134
changing Joseph Liemandt, Andra Liemandt to Liemandt, Joseph and Andra because lobbyist[5] is 625
changing Greystone Steiner Associates to The Greystone Group because lobbyist[5] is 419
changing Kerbey Lane Doll Shoppe to Kerbey Lane Cafe because lobbyist[5] is 305
changing Fineline Diversivied Development to Fine Line Diversified Development because lobbyist[5] is 628
changing David and Suzanne Booth to David and Suzanne Booth because lobbyist[5] is 47
changing Paz Dhody to Paz Doty because lobbyist[5] is 357
changing Circuit of the Americas to Circuit of the Americas because lobbyist[5] is 105
changing CWS to CWS Capital Partners because lobbyist[5] is 355
changing John Calhoun Miller to Miller, John Calhoun because lobbyist[5] is 717
changing Austaco to Tacala dba Taco Bell because lobbyist[5] is 755
changing Brigid Cockrum to Cockrum, Brigid because lobbyist[5] is 561
changing Raptor Air to General Aviation Avenue, LLc because lobbyist[5] is 540
changing BusGuard to Force Multiplier Solutions because lobbyist[5] is 524
changing Texas Star Brands to Texas Star Brands because lobbyist[5] is 184
changing 620/183 to 620/183 because lobbyist[5] is 153
changing LTBS 2222 to LTBS 2222 because lobbyist[5] is 154
changing Capital Metro to Capital Metro because lobbyist[5] is 495
changing Apple Inc. to Apple because lobbyist[5] is 490
changing Colina West Real Estate to Colina West Real Estate because lobbyist[5] is 103
changing Wal-Mart Stores, Inc to Wal-Mart because lobbyist[5] is 224
changing Little City Properties to Little City Properties because lobbyist[5] is 405
changing 2208 Lake Austin to 2208 Lake Austin because lobbyist[5] is 857
changing RKS Texas Investments to RKS Texas Investments because lobbyist[5] is 809
changing Austin HB Residential to Harris Branch Master Association because lobbyist[5] is 457
changing CBL and Associates Management to CBL and Associates Management because lobbyist[5] is 268
changing Sunshine Camp to Austin Sunshine Camp because lobbyist[5] is 257

In [111]:
from fuzzywuzzy import fuzz
import re

# Wrangling lobbyist names

for lobbyist in lobbyists:
    lobbyist[2] = lobbyist[2].rstrip()
    lobbyist[2] = lobbyist[2].replace('  ',' ')
    lobbyist[2] = lobbyist[2].replace('"Trey S','"Trey" S')
    lobbyist[2] = lobbyist[2].replace('"Smitty ','"Smitty" ')
    lobbyist[2] = lobbyist[2].replace('Salda?a','Saldaña')
    lobbyist[2] = re.sub('Amelia Lopez$','Amelia Lopez Saltarelli',lobbyist[2])
    lobbyist[2] = lobbyist[2].replace('Bob Digneo','Robert Digneo')
    lobbyist[2] = lobbyist[2].replace('Gerbracht Heidi','Heidi Gerbracht')
    lobbyist[2] = lobbyist[2].replace('Wunsch Karen','Karen Wunsch')
    
uniqueL = []
for lobbyist in lobbyists:
    if lobbyist[2] not in uniqueL:
        uniqueL.append(lobbyist[2])
    
for person in uniqueL:
    for other in uniqueL:
        if person != other and fuzz.token_set_ratio(person, other) > 90:
            print(other + ' changed to ' + person)
            for lobbyist in lobbyists:
                if lobbyist[2] == other:
                    lobbyist[2] = person
            uniqueL.remove(other)

            '''
    lobbyist[2] = lobbyist[2].replace('Katie King Ogden','Katie Ogden')
    lobbyist[2] = lobbyist[2].replace('Bustamante Christine','Christine Bustamante')
    
    '''

# below is just to look at what values are in the list

newL = []
for lobbyist in lobbyists:
    if lobbyist[2] not in newL:
        newL.append(lobbyist[2])
newL.sort()   
print(newL)

Katie Ogden changed to Katie King Ogden
Tahuahua Geoffrey changed to Geoffrey Tahuahua
['Adam Goldman', 'Alexandra Jashinsky', 'Alice Glasco', 'Alice Myers', 'Alison Gardner', 'Allen Halbrook', 'Allen Thrower', 'Amanda Morrow', 'Amanda Swor', 'Amber Pearce', 'Amelia Lopez Saltarelli', 'Andrei Lubomudrov', 'Anne Clutterbuck', 'Ashton Cumberbatch', 'Betty Dunkerley', 'Brandon Aghamalian', 'Brian Bower', 'Brian Thompson', 'Bustamante Christine', 'Carlos Lopez', 'Carolyn Rupprath', 'Carolyn Walsh', 'Casey McKinney', 'Cheryl Burtzel', 'Christina Holch', 'Chuck Rice', 'Craig Chick', 'Darren Kolack', 'David Anderson', 'David Armbrust', 'David Cancialosi', 'David Hartman', 'David Herndon', 'David Nichols', 'Deborah Reyes', 'Derek Villemez', 'Derlis "Trey" Salinas III', 'Donald Lucardi', 'Donald Martin', 'Dowe Gullatt', 'Edward Shack', 'Elise Wood', 'Emily Chenevert', 'Emily Lubbers', 'Emily Timm', 'Eric deYoung', 'Erin Burget', 'Evangelina Munoz', 'Frank Del Castillo', 'Gay Erwin', 'Geoffrey Tahuahua', 'Gerard Branka', 'Gerardo Interiano', 'Geronimo Rodriguez', 'Glen Coleman', 'Glenn Shankle', 'Gregorio Casar', 'Gregory Hartman', 'Heidi Gerbracht', 'Henry Gilmore', 'Holly Desheilds', 'Jack Gullahorn', 'Jack Kirfman', 'James Cousar', 'Janice Cartwright', 'Jay Hailey', 'Jed Buie', 'Jeffrey Heckler', 'Jeffrey Howard', 'Jennifer Houlihan', 'Jeremy Martin', 'Jerry Harris', 'Jesus Garza', 'Jimmy Bennett Sr.', 'Joe Garcia', 'Joel Romo', 'John Carlton', 'John Donisi', 'John Joseph', 'Jose Carrillo', 'Joseph Lessard', 'Josh Fritzsche', 'Kaitlyn Murphy', 'Karen Wunsch', 'Katie King Ogden', 'Kelan Robinson', 'Kelly Mike', 'Kelsey Bernstein', 'Kevin Flahive', 'Laura Spanjian', 'Leah Bojo', 'Leonard Smith', 'Leslie Ward', 'Lynn Carley', 'Manuel Escobar', 'Mark Littlefield', 'Martha Harris', 'Mary Nabers', 'Mary Stratmann', 'Melody Clark', 'Michael Peterson', 'Michael Whellan', 'Michele Haussmann', 'Michele Lynch', 'Mike Meroney', 'Mike Peterson', 'Miller Christopher', 'Nancy Siefken', 'Nicholas Miller', 'Nikelle Meade', 'Pamela Madere', 'Paul Saldaña', 'Pete Winstead', 'Peter Brown', 'Peter Cesaro', 'Philip Haag', 'R. Haywood', 'Rachel Fisher', 'Ray Allen', 'Rebecca Moss', 'Richard Suttle', 'Richard Szecsy', 'Rick Triplett', 'Robert Delp', 'Robert Digneo', 'Robert Kleeman', 'Robert Levinski', 'Roger Duncan', 'Ronnie Volkening', 'Royce Poinsett', 'Ryan Thompson', 'Sarah Crocker', 'Scott Miller', 'Shannon Meroney', 'Shannon Noble', 'Sheryl Cole', 'Snapper Carr', 'Stepane Gharakhanian', 'Stephen Butler', 'Stephen Drenner', 'Stephen Rye', 'Steven Metcalfe', 'Teakell Randall', 'Terrence Irion', 'Terri Broussard Williams', 'Theodore Wickersham, Jr.', 'Timothy Arndt', 'Tom "Smitty" Smith', 'Travis Phillips', 'Vaughn Richard', 'Ward Tisdale', 'Will Wynn', 'William Berger', 'William Bingham', 'William Francis', 'Wm. Bray', 'Yuniedth Steen']

In [112]:
# I'm hesitant to use the industry field in any way.

for lobbyist in lobbyists:
    lobbyist[4] = lobbyist[4].rstrip()
    lobbyist[4] = lobbyist[4].replace('  ',' ')
    lobbyist[4] = re.sub(' Corporation$','', lobbyist[4])
    lobbyist[4] = lobbyist[4].replace("\x19","'")
    
uniqueI = []
for lobbyist in lobbyists:
    if lobbyist[4] not in uniqueI:
        uniqueI.append(lobbyist[4])

uniqueI.sort()   
print(uniqueI)

['', '1023 Springdale TIA/Zoning', 'Advertising', 'Advocavy Organization', 'Affordable Housing', 'Affordable Housing Developers', 'Airlines', 'Apartment Development', 'Apartment Management', 'Architect', 'Architecture, engineering and planning services', 'Association', 'Austin Film Industry', 'Auto Salvage', 'Automaker', 'Automated Traffic Enforcement', 'Automotive Sales', 'Banking Association', 'Banking/Finance', 'Builder', 'Builders', 'Building Contractor', 'Building Products', 'Bus System', 'Business Association', 'Business League', 'Business Owner', 'Business Owner & Property Developer', 'Car Dealership', 'Car Wash', 'Catering and Event Services', 'Charity and Real Estate', 'Child Safety', 'Church', 'Commercial Real Property Management', 'Commerical Real Property Management', 'Community Association', 'Community College', 'Community Historic Preservation Group', 'Computer and Consumer Electronic Products', 'Condo Propert Owners', 'Condominium Association', 'Construct house and boatdock', 'Construction', 'Construction Firm', 'Construction Procurement Solutions', 'Construction Services', 'Construction Trade Association', 'Consulting and Research', 'Consulting,Conservation, Lobbying', 'Consumer Lending', 'Contractor', 'Contractors', 'Convention and Hospitality Management', 'Cultural Arts Organization', 'Customer Services', 'Database Solutions', 'Debt Collection', 'Dentist', 'Design, Testing, Packaging and Marketing of Integraded Circuits', 'Developement of parking facilities at the airport', 'Developer', 'Developer/Builder', 'Development', 'Development of FBO site at ABIA', 'Education', 'Education/ Social Service Organization/Economic Development Corp', 'Electric Coop', 'Electric Energy Provider', 'Emergency Services', 'Energy', 'Energy Efficient Contract', 'Energy Related Issues', 'Engerneering, Consulting Professional Services', 'Engineer', 'Engineering', 'Engineering Firm', 'Engineering Services', 'Engineers', 'Engu=ineering', 'Entertainment', 'Entertainment Industry', 'Environmental Advocacy', 'Environmental Protection', 'Event Company', 'Event Manager', 'Excavation', 'Facility Services', 'Fast Food', 'Film Industry', 'Financial Institutions', 'Financial Services', 'Financing/Development', 'Florist', 'Food Disposal', 'General Business', 'Golf Course', 'Grocery Store', 'HR Services', 'Health Care Facilities', 'Health Center', 'Healthcare Network', 'Healthcare Provider', 'Healthcare Providor', 'High Tech', 'Home Builder', 'Home Owner', 'Homebuilder', 'Homeowner', 'Hotel', 'Hotel Developers', 'Hotel/Resort', 'House Permits', 'Housing Authority', 'Housing Development', 'Individual', 'Information Technology', 'Information Technology Staffing', 'Infrastructure', 'Insurance', 'Intermunicipal Commuter Rail District planning service', 'Investment, development, zoning and related activities', 'Labor Union', 'Lake Austin Issues', 'Land Developement', 'Land Developement Code Related Issues', 'Land Developers', 'Land Development', 'Land Development & Sales', 'Land Development Code Related Issues', 'Land Development Company', 'Land Management', 'Land Owner', 'Land Use Development', 'Land use', 'Land use and development', 'Land use consulting', 'Law Firm', 'Law Office', 'Legal', 'Lender', 'Limited District', 'Limo and Bus Service', 'Live Music', 'Live Music and Real Estate Development', 'MBE/WBE Issues', 'Mailing Services', 'Manufactured Home Community Builder', 'Master Planning', 'Mobile Catering', 'Mobile Vending', 'Multi-family Development', 'Municipal District', 'Municipal Utility District', 'Music Industry', 'Neghborhood Association', 'Neighborhood Asociation', 'Neighborhood Assoc', 'Neighborhood Association', 'Network deployment, development, zoning and signage issues', 'Non profit Cultural Arts', 'Non- Profit', 'Non-Profit', 'Non-Profit Company', 'Non-Profit Educational Charity', 'Non-profit', 'Non-profit Public Health Organization', 'Not-for-profit entity for dev. of Waller Creek Project.', 'Off-airport parking provider', 'On Demand Valet Parking Service', 'Oursourcing Services', 'Outdoor Advertising', 'Parking', 'Parking Enforcement', 'Parks and Trails', 'Permitting', 'Pet Adoption', 'Pharmaceutical Manufacturing and Healthcare', 'Plastics Recycling Company', 'Practice of Law', 'Private Property Owner', 'Private Property Owner/Real Estate Investment/Development', 'Private School', 'Private Vehicle Immobilizaion', 'Procurement', 'Promotions', 'Property Developer', 'Property Development', 'Property Management', 'Property Management; Real Estate Services', 'Property Owner', 'Property Owner/ Developer', 'Property Owner/Developer', 'Property Owner/Manager', 'Property Owners', 'Proposed Office Project', 'Prospective Taxi Franchise', 'Provider & Applicator of Manhole Coatings and Wastewater Pipe Linings', 'Provides internet related products and services', 'Public Affairs', 'Public Relations, Marketing Advertising, Real Estate/Constru', 'Public School', 'Public Schools', 'Purchase of Bond Debt', 'Quick Food Service', 'Quick Service Food', 'Radio Station', 'Railroad', 'Real', 'Real Estate', 'Real Estate Broker', 'Real Estate Develoment', 'Real Estate Developement', 'Real Estate Developer', 'Real Estate Developers', 'Real Estate Development', 'Real Estate Development/ Investment', 'Real Estate Entitlement', 'Real Estate Investment', 'Real Estate Investment Management', 'Real Estate Investment/ Development', 'Real Estate Investment/Development', 'Real Estate Investment/Development (Canada M5J2TE Address)', 'Real Estate Investor', 'Real Estate and Non-Profit', 'Real Estate investment/ development', 'Real Estate/Investment', 'Real Property Owner', 'Real Property Owners', 'Real Propery Owner', 'Real estate development', 'Real estate related issues', 'Recycling Company', 'Related land development issues', 'Religious Assembly', 'Religious Assembly/Education', 'Religious Organization', 'Renewable Energy', 'Renewable Energy Development', 'Rental Properties', 'Residentaial Entitlement', 'Residential', 'Residential Entitelement', 'Residential Entitlement', 'Resl Estate Development', 'Restaurant', 'Restaurant Association', 'Restaurant Operator', 'Restaurant Owner', 'Restaurant/Bar', 'Restaurants', 'Retail Merchant', 'Retail Sales', 'Sales, Business and Rental', 'Sand and gravel mining', 'School', 'Short Term Rentals', 'Short term rentals', 'Sign Contractor', 'Software Applications', 'Solar Company', 'Solar Energy Provider', 'Solar Power Company', 'Solar energy provider', 'Special event', 'Specialty food, retail and merchandise stores', 'Specialty food,beverage and retail concessions and merchandise', 'Sports and Special Events Productions', 'State association for concrete industry', 'Systems Integration and Data Centers', 'Taxi Cab', 'Taxicab', 'Taxicab Company', 'Technology', 'Technology/Secure Data Storage', 'Telecommunications', 'Television network', 'Title Company', 'Tourism', 'Towing', 'Towing, storage and disposition of vehicles', 'Trade Association', 'Trade Association and Retailers', 'Transportation', 'Tree Trimming', 'Uniform Co', 'Union/Political', 'University', 'Urban Farm', 'Utility District', 'Vacation Rental Service', 'Waste Disposal', 'Waste Recycling & Residuals', 'Waste management and recycling', 'Water & Energy Conservation', 'Water District Issues', 'Water Resources', 'Water, Parks', 'Web Based Services', 'Wireless Communications Services', 'Wireless Infrastructure', 'Workforce Solutions', 'Youth Recreational Facility', 'Zoning', 'Zoning Issues', 'Zoning, subdivision, affordable housing', 'Zoning/Land Development', 'Zonng']

In [113]:
# checking to see if the dates are strings or datetimes right now.

q = type(lobbyists[1][0])
print(q)
print(lobbyists[1][0])

print("lobbyists " + str(len(lobbyists)))

# This is to get rid of multiple entries for the same person hired to rep related entities on the same day.

newl = []
for i in lobbyists:
    if i not in newl:
        newl.append(i)

print("newl " + str(len(newl)))

for first in newl:
    for second in newl:
        if first[:4] == second[:4] and first[4] != second[4]:
            if "Zoning" in first[4] or "Property" in first[4]:
                print(str(first) + " industry deleted in favor of " + str(second))
                newl.remove(first)
            else:
                print(str(second) + " industry deleted in favor of " + str(first))
                newl.remove(second)

<class 'datetime.date'>
2013-12-20
lobbyists 7718
newl 3499
[datetime.date(2014, 4, 24), datetime.date(2015, 4, 24), 'Rachel Fisher', 'Austin Apartment Association', 'Association', 804] industry deleted in favor of [datetime.date(2014, 4, 24), datetime.date(2015, 4, 24), 'Rachel Fisher', 'Austin Apartment Association', 'Apartment Management', 935]
[datetime.date(2014, 1, 3), datetime.date(2015, 1, 3), 'Michael Whellan', 'SXSW', 'Property Owner', 683] industry deleted in favor of [datetime.date(2014, 1, 3), datetime.date(2015, 1, 3), 'Michael Whellan', 'SXSW', 'Entertainment Industry', 642]
[datetime.date(2014, 1, 3), datetime.date(2015, 1, 3), 'R. Haywood', 'SXSW', 'Property Owner', 683] industry deleted in favor of [datetime.date(2014, 1, 3), datetime.date(2015, 1, 3), 'R. Haywood', 'SXSW', 'Music Industry', 641]
[datetime.date(2014, 1, 3), datetime.date(2015, 1, 3), 'Rick Triplett', 'SXSW', 'Property Owner', 683] industry deleted in favor of [datetime.date(2014, 1, 3), datetime.date(2015, 1, 3), 'Rick Triplett', 'SXSW', 'Music Industry', 641]
[datetime.date(2014, 1, 3), datetime.date(2015, 1, 3), 'Peter Cesaro', 'SXSW', 'Property Owner', 683] industry deleted in favor of [datetime.date(2014, 1, 3), datetime.date(2015, 1, 3), 'Peter Cesaro', 'SXSW', 'Music Industry', 641]
[datetime.date(2013, 1, 3), datetime.date(2014, 1, 3), 'Nicholas Miller', 'SXSW', 'Property Owner', 683] industry deleted in favor of [datetime.date(2013, 1, 3), datetime.date(2014, 1, 3), 'Nicholas Miller', 'SXSW', 'Music Industry', 641]
[datetime.date(2013, 1, 3), datetime.date(2014, 1, 3), 'Nicholas Miller', 'Zydeco Development', 'Zoning', 459] industry deleted in favor of [datetime.date(2013, 1, 3), datetime.date(2014, 1, 3), 'Nicholas Miller', 'Zydeco Development', 'Real Estate Development', 462]
[datetime.date(2013, 1, 3), datetime.date(2014, 1, 3), 'Wm. Bray', 'SXSW', 'Property Owner', 683] industry deleted in favor of [datetime.date(2013, 1, 3), datetime.date(2014, 1, 3), 'Wm. Bray', 'SXSW', 'Music Industry', 641]
[datetime.date(2013, 1, 3), datetime.date(2014, 1, 3), 'Wm. Bray', 'Zydeco Development', 'Zoning', 459] industry deleted in favor of [datetime.date(2013, 1, 3), datetime.date(2014, 1, 3), 'Wm. Bray', 'Zydeco Development', 'Real Estate Development', 462]
[datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Amanda Morrow', 'David and Suzanne Booth', 'Real Estate investment/ development', 47] industry deleted in favor of [datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Amanda Morrow', 'David and Suzanne Booth', 'Real Estate Investment/Development', 168]
[datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Lynn Carley', 'Walton International Group', 'Real Estate Development', 560] industry deleted in favor of [datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Lynn Carley', 'Walton International Group', 'Real Estate Investment/Development (Canada M5J2TE Address)', 194]
[datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Amanda Morrow', 'Deborah and Gary Attal', 'Private Property Owner', 166] industry deleted in favor of [datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Amanda Morrow', 'Deborah and Gary Attal', 'Real Estate Development/ Investment', 410]
[datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Lynn Carley', 'David and Suzanne Booth', 'Real Estate investment/ development', 47] industry deleted in favor of [datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Lynn Carley', 'David and Suzanne Booth', 'Real Estate Investment/Development', 168]
[datetime.date(2015, 1, 12), datetime.date(2016, 1, 12), 'John Donisi', 'Roy Cavanaugh', 'Property Owner', 270] industry deleted in favor of [datetime.date(2015, 1, 12), datetime.date(2016, 1, 12), 'John Donisi', 'Roy Cavanaugh', 'Real Estate', 271]
[datetime.date(2015, 1, 12), datetime.date(2016, 1, 12), 'Leah Bojo', 'Austin Fairchild Management', 'Real Estate Developement', 95] industry deleted in favor of [datetime.date(2015, 1, 12), datetime.date(2016, 1, 12), 'Leah Bojo', 'Austin Fairchild Management', 'Real Estate', 959]
[datetime.date(2015, 1, 20), datetime.date(2016, 1, 20), 'David Armbrust', 'David and Suzanne Booth', 'Real Estate investment/ development', 47] industry deleted in favor of [datetime.date(2015, 1, 20), datetime.date(2016, 1, 20), 'David Armbrust', 'David and Suzanne Booth', 'Real estate related issues', 50]
[datetime.date(2015, 1, 30), datetime.date(2016, 1, 30), 'Michael Whellan', 'SXSW', 'Property Owner', 683] industry deleted in favor of [datetime.date(2015, 1, 30), datetime.date(2016, 1, 30), 'Michael Whellan', 'SXSW', 'Entertainment Industry', 642]
[datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Amanda Morrow', 'H-E-B', 'Grocery Store', 545] industry deleted in favor of [datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Amanda Morrow', 'H-E-B', 'Real Estate', 39]
[datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Lynn Carley', 'H-E-B', 'Real Estate Investment', 31] industry deleted in favor of [datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Lynn Carley', 'H-E-B', 'Real Estate', 39]
[datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Amanda Morrow', 'Gables Residential', 'Real Estate Investment/Development', 873] industry deleted in favor of [datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Amanda Morrow', 'Gables Residential', 'Real Estate Investment', 107]
[datetime.date(2014, 12, 23), datetime.date(2015, 12, 23), 'Richard Suttle', 'H-E-B', 'Real Estate Investment', 31] industry deleted in favor of [datetime.date(2014, 12, 23), datetime.date(2015, 12, 23), 'Richard Suttle', 'H-E-B', 'Real Estate', 39]
[datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Amanda Morrow', 'North Austin MUD No. 1', 'Real Estate', 36] industry deleted in favor of [datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Amanda Morrow', 'North Austin MUD No. 1', 'Municipal Utility District', 89]
[datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Lynn Carley', 'Deborah and Gary Attal', 'Private Property Owner', 166] industry deleted in favor of [datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Lynn Carley', 'Deborah and Gary Attal', 'Real Estate Development/ Investment', 410]
[datetime.date(2014, 10, 21), datetime.date(2015, 10, 21), 'David Cancialosi', 'Brian Follett', 'Residential Entitlement', 528] industry deleted in favor of [datetime.date(2014, 10, 21), datetime.date(2015, 10, 21), 'David Cancialosi', 'Brian Follett', 'Residentaial Entitlement', 963]
[datetime.date(2014, 12, 23), datetime.date(2015, 12, 23), 'Richard Suttle', 'Robert Schmidt', 'Private Property Owner', 94] industry deleted in favor of [datetime.date(2014, 12, 23), datetime.date(2015, 12, 23), 'Richard Suttle', 'Robert Schmidt', 'Real Estate Investment/Development', 571]
[datetime.date(2015, 1, 12), datetime.date(2016, 1, 12), 'Stephen Drenner', 'Roy Cavanaugh', 'Property Owner', 270] industry deleted in favor of [datetime.date(2015, 1, 12), datetime.date(2016, 1, 12), 'Stephen Drenner', 'Roy Cavanaugh', 'Real Estate', 271]
[datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Lynn Carley', 'Robert Schmidt', 'Private Property Owner', 94] industry deleted in favor of [datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Lynn Carley', 'Robert Schmidt', 'Real Estate Investment/Development', 571]
[datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Lynn Carley', 'Gables Residential', 'Real Estate Investment/Development', 873] industry deleted in favor of [datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Lynn Carley', 'Gables Residential', 'Real Estate Investment', 107]
[datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Amanda Morrow', 'Highland Management', 'Real Estate Development', 705] industry deleted in favor of [datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Amanda Morrow', 'Highland Management', 'Real Estate', 704]
[datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Lynn Carley', 'Highland Management', 'Real Estate Development', 705] industry deleted in favor of [datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Lynn Carley', 'Highland Management', 'Real Estate', 704]
[datetime.date(2014, 12, 23), datetime.date(2015, 12, 23), 'Richard Suttle', 'Highland Management', 'Real Estate Development', 705] industry deleted in favor of [datetime.date(2014, 12, 23), datetime.date(2015, 12, 23), 'Richard Suttle', 'Highland Management', 'Real Estate', 704]
[datetime.date(2014, 12, 23), datetime.date(2015, 12, 23), 'Richard Suttle', 'Deborah and Gary Attal', 'Private Property Owner', 166] industry deleted in favor of [datetime.date(2014, 12, 23), datetime.date(2015, 12, 23), 'Richard Suttle', 'Deborah and Gary Attal', 'Real Estate Development/ Investment', 410]
[datetime.date(2014, 12, 23), datetime.date(2015, 12, 23), 'Richard Suttle', 'The Brohn Group', 'Real Estate', 170] industry deleted in favor of [datetime.date(2014, 12, 23), datetime.date(2015, 12, 23), 'Richard Suttle', 'The Brohn Group', 'Real Estate Investment/Development', 171]
[datetime.date(2014, 12, 23), datetime.date(2015, 12, 23), 'Richard Suttle', 'Walton International Group', 'Real Estate Development', 560] industry deleted in favor of [datetime.date(2014, 12, 23), datetime.date(2015, 12, 23), 'Richard Suttle', 'Walton International Group', 'Real Estate Investment/Development (Canada M5J2TE Address)', 194]
[datetime.date(2014, 12, 23), datetime.date(2015, 12, 23), 'Richard Suttle', 'Seton Healthcare', 'Healthcare Provider', 658] industry deleted in favor of [datetime.date(2014, 12, 23), datetime.date(2015, 12, 23), 'Richard Suttle', 'Seton Healthcare', 'Real Estate', 201]
[datetime.date(2014, 12, 23), datetime.date(2015, 12, 23), 'Richard Suttle', 'Gables Residential', 'Real Estate Investment/Development', 873] industry deleted in favor of [datetime.date(2014, 12, 23), datetime.date(2015, 12, 23), 'Richard Suttle', 'Gables Residential', 'Real Estate Investment', 107]
[datetime.date(2014, 12, 23), datetime.date(2015, 12, 23), 'Richard Suttle', 'Onion Associates', 'Real Estate Investment/ Development', 887] industry deleted in favor of [datetime.date(2014, 12, 23), datetime.date(2015, 12, 23), 'Richard Suttle', 'Onion Associates', 'Real Estate', 204]
[datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Lynn Carley', 'Onion Associates', 'Real Estate Investment/ Development', 887] industry deleted in favor of [datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Lynn Carley', 'Onion Associates', 'Real Estate', 204]
[datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Amanda Morrow', 'Onion Associates', 'Real Estate Investment/ Development', 887] industry deleted in favor of [datetime.date(2015, 1, 6), datetime.date(2016, 1, 6), 'Amanda Morrow', 'Onion Associates', 'Real Estate', 204]
[datetime.date(2015, 2, 2), datetime.date(2016, 2, 2), 'R. Haywood', 'SXSW', 'Property Owner', 683] industry deleted in favor of [datetime.date(2015, 2, 2), datetime.date(2016, 2, 2), 'R. Haywood', 'SXSW', 'Music Industry', 641]
[datetime.date(2015, 2, 2), datetime.date(2016, 2, 2), 'Rick Triplett', 'SXSW', 'Property Owner', 683] industry deleted in favor of [datetime.date(2015, 2, 2), datetime.date(2016, 2, 2), 'Rick Triplett', 'SXSW', 'Music Industry', 641]
[datetime.date(2015, 2, 2), datetime.date(2016, 2, 2), 'Peter Cesaro', 'SXSW', 'Property Owner', 683] industry deleted in favor of [datetime.date(2015, 2, 2), datetime.date(2016, 2, 2), 'Peter Cesaro', 'SXSW', 'Music Industry', 641]
[datetime.date(2014, 12, 23), datetime.date(2015, 12, 23), 'Richard Suttle', 'David and Suzanne Booth', 'Real Estate Investment/Development', 168] industry deleted in favor of [datetime.date(2014, 12, 23), datetime.date(2015, 12, 23), 'Richard Suttle', 'David and Suzanne Booth', 'Real Estate investment/ development', 47]
[datetime.date(2016, 1, 20), datetime.date(2017, 1, 19), 'David Armbrust', 'David and Suzanne Booth', 'Real Estate investment/ development', 47] industry deleted in favor of [datetime.date(2016, 1, 20), datetime.date(2017, 1, 19), 'David Armbrust', 'David and Suzanne Booth', 'Real estate related issues', 50]
[datetime.date(2016, 1, 5), datetime.date(2017, 1, 4), 'Michael Whellan', 'SXSW', 'Property Owner', 683] industry deleted in favor of [datetime.date(2016, 1, 5), datetime.date(2017, 1, 4), 'Michael Whellan', 'SXSW', 'Entertainment Industry', 642]
[datetime.date(2015, 12, 24), datetime.date(2016, 12, 23), 'Richard Suttle', 'Cypress Realty', 'Real Estate Development', 112] industry deleted in favor of [datetime.date(2015, 12, 24), datetime.date(2016, 12, 23), 'Richard Suttle', 'Cypress Realty', 'Real Estate Investment/Development', 104]
[datetime.date(2016, 1, 7), datetime.date(2017, 1, 6), 'Lynn Carley', 'Cypress Realty', 'Real Estate Investment/Development', 104] industry deleted in favor of [datetime.date(2016, 1, 7), datetime.date(2017, 1, 6), 'Lynn Carley', 'Cypress Realty', 'Real Estate Development', 112]
[datetime.date(2016, 1, 13), datetime.date(2017, 1, 12), 'Rick Triplett', 'SXSW', 'Property Owner', 683] industry deleted in favor of [datetime.date(2016, 1, 13), datetime.date(2017, 1, 12), 'Rick Triplett', 'SXSW', 'Entertainment Industry', 642]
[datetime.date(2016, 1, 13), datetime.date(2017, 1, 12), 'Peter Cesaro', 'SXSW', 'Property Owner', 683] industry deleted in favor of [datetime.date(2016, 1, 13), datetime.date(2017, 1, 12), 'Peter Cesaro', 'SXSW', 'Entertainment Industry', 642]
[datetime.date(2016, 1, 7), datetime.date(2017, 1, 6), 'Amanda Morrow', 'Cypress Realty', 'Real Estate Development', 112] industry deleted in favor of [datetime.date(2016, 1, 7), datetime.date(2017, 1, 6), 'Amanda Morrow', 'Cypress Realty', 'Real Estate Investment/Development', 104]

In [114]:
# The next block is intended to delete entries that represent the same lobbyist merely renewing a registration.
# I'm assuming that the same representation is continuing if there's a gap of less than 180 days in 
# the lobbyist's registration. I picked the number 180 out of thin air.

extensions = 0

print(newl[1])

for first in newl:
    for second in newl:
        if first[2:4] == second[2:4] and second[0] > first[0] and second[0] < (first[1] + datetime.timedelta(days=180)):
            # print("for " + first[2] + " " + first[3] + " extending " + str(first[1]) + " to " + str(second[1]))
            first[1] = second[1]
            extensions = extensions + 1
            newl.remove(second)

print('deleted ' + str(extensions) + ' extensions.')

[datetime.date(2013, 12, 20), datetime.date(2014, 12, 20), 'Richard Suttle', 'Tierra Concepts', 'Real Estate Investment/Development', 4]
deleted 1477 extensions.

In [115]:
# putting data in pandas

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

lobbyFrame = pd.DataFrame(newl, columns=('Start', 'End', 'Lobbyist', 'Client', 'Industry', 'Cluster'))

lobbyFrame.describe()

           Cluster
count  1972.000000
mean    466.504057
std     286.090606
min       0.000000
25%     196.750000
50%     463.000000
75%     718.250000
max     981.000000

In [116]:
lobbyFrame.sort_values(by='Start')
lobbyFrame.head(10)

,Start,End,Lobbyist,Client,Industry,Cluster
0,2013-12-20,2016-12-23,Richard Suttle,Forestar Real Estate Group,Land Development & Sales,46
1,2013-12-20,2016-12-23,Richard Suttle,Tierra Concepts,Real Estate Investment/Development,4
2,2013-12-20,2016-12-23,Richard Suttle,Majestic Realty,Real Estate Investment,123
3,2013-12-20,2016-12-23,Richard Suttle,"Cullen, John",Real Estate Investment,6
4,2013-12-20,2016-12-23,Richard Suttle,The NRP Group,Real Estate Investment,8
5,2013-12-20,2016-12-23,Richard Suttle,The Charter School Fund,Public School,10
6,2013-12-20,2016-12-23,Richard Suttle,"Rice, Robert",Real Estate Investment,12
7,2013-12-20,2016-12-23,Richard Suttle,"Wilkerson, Eric",Real Estate Investment,14
8,2013-12-20,2016-12-23,Richard Suttle,Riddell Family,Real Estate Investment,16
9,2013-12-20,2016-12-23,Richard Suttle,AutoReturn,Real Estate Investment,859

In [117]:
lastDay = lobbyFrame['Start'].max() # This is the end date of the line chart!!
print(lastDay)

2016-03-14

In [118]:
# making a new output file:

outputFile = open('lobbyistTimeRange.csv', 'w', newline='')
outputWriter = csv.writer(outputFile)
outputWriter.writerow(['Start', 'End', 'Lobbyist', 'Client', 'Industry', 'Cluster'])
for row in newl:
    outputWriter.writerow(row)
outputFile.close()

In [119]:
lobbyFrame['Client'].value_counts()

AT&T                                             14
Seton Healthcare                                 13
Riverside Resources Investments, Limited         11
Met Center                                       10
American Heart Association                        9
Forestar Real Estate Group                        9
Spire Realty                                      8
The NRP Group                                     8
Highland Management                               8
Reagan National Advertising                       8
Austin Board of Realtors                          8
Endeavor Real Estate Group                        8
Simon Property Group                              7
International Bank of Commerce, Laredo, Texas     7
Cypress Realty                                    7
Zydeco Development                                6
The Brohn Group                                   6
Texas Disposal Systems                            6
Twin Oaks Associates                              6
Republic Services of Austin                       6
Circuit of the Americas                           6
Lorenz, Perry                                     6
Dwyer Realty Companies                            6
Brandywine Realty Trust                           6
CWS Capital Partners                              6
St. David's Foundation                            6
H-E-B                                             6
Finley Company                                    6
SXSW                                              6
The University of Texas System                    6
                                                 ..
Criterion Development Partners                    1
SNAP Set                                          1
Community Sun                                     1
Travis Entitlements                               1
Universal Health Services                         1
Lee's Meat Market                                 1
Canchola and Hyde Productions                     1
Permit Partners                                   1
Spurs Sports and Entertainment                    1
Montana Builders                                  1
DFI Resources                                     1
General Aviation Avenue, LLc                      1
Russell's Bakery                                  1
Scotia Western States Housing                     1
Triton Receivership                               1
MWH Constructors                                  1
Essex and Delancey                                1
1210 Barton Springs Road Venture                  1
Ron White Garza Estate                            1
Cobalt Partners, Limited                          1
Tan Min Ho                                        1
Andersson Wise Architects                         1
Dana Copp Builder                                 1
Save Our Springs Alliance                         1
Noble Savage Design/Build                         1
JBS Holdings                                      1
Mission Homes                                     1
Verbena Design Studio                             1
Heiser Development                                1
Cypress Semiconductor                             1
Name: Client, dtype: int64

In [120]:
'''
I'm trying to find every group of rows with the same Date and Client, and replace them with a single row with the
sum of the old Change values as the new Change value.
    '''

changes = []
for lobbyist in newl:
    # start date, client name, add one
    changes.append([lobbyist[0], lobbyist[3], 1])
    changes.append([lobbyist[1], lobbyist[3], -1])

In [121]:
cumFrame = pd.DataFrame(changes, columns=('Date', 'Client', 'Change'))
# cumFrame['Date'] = pd.to_datetime(cumFrame.Date)
cumFrame = cumFrame.sort_values('Date')

print(cumFrame.loc[cumFrame['Client'] == 'AT&T'])

            Date Client  Change
796   2013-06-18   AT&T       1
696   2013-08-06   AT&T       1
700   2013-08-06   AT&T       1
702   2013-08-06   AT&T       1
698   2013-08-06   AT&T       1
692   2013-08-07   AT&T       1
694   2013-08-07   AT&T       1
688   2013-08-13   AT&T       1
334   2013-10-07   AT&T       1
348   2013-10-07   AT&T       1
320   2013-10-08   AT&T       1
701   2014-08-06   AT&T      -1
697   2014-08-06   AT&T      -1
689   2014-08-13   AT&T      -1
3362  2015-03-06   AT&T       1
693   2015-08-20   AT&T      -1
703   2015-08-20   AT&T      -1
695   2015-08-20   AT&T      -1
3134  2015-09-19   AT&T       1
335   2015-10-15   AT&T      -1
3924  2016-03-04   AT&T       1
797   2016-06-12   AT&T      -1
699   2016-08-04   AT&T      -1
3135  2016-09-18   AT&T      -1
349   2016-10-09   AT&T      -1
321   2016-10-22   AT&T      -1
3363  2017-03-04   AT&T      -1
3925  2017-03-04   AT&T      -1

In [122]:
cFrame = cumFrame.groupby(('Client','Date')).sum()

cFrame.head(20)

                                             Change
Client                           Date
1000 E. 6th                      2014-08-20       1
                                 2015-08-20      -1
1023 Holdings                    2015-06-16       1
                                 2016-06-15      -1
1210 Barton Springs Road Venture 2014-03-31       1
                                 2016-03-31      -1
1219 South Lamar Venture         2013-01-03       2
                                 2014-01-03      -1
                                 2015-01-03      -1
16 Piggybank                     2014-07-09       1
                                 2014-12-21       1
                                 2015-01-12       1
                                 2016-01-12      -2
                                 2016-07-20      -1
1600 West 38th                   2010-12-16       1
                                 2011-12-16      -1
1715 G                           2015-04-24       1
                                 2015-06-27       1
                                 2016-04-23      -1
                                 2016-06-26      -1

In [123]:
cFrame.reset_index(inplace=True)  
cFrame.head(20)

                              Client        Date  Change
0                        1000 E. 6th  2014-08-20       1
1                        1000 E. 6th  2015-08-20      -1
2                      1023 Holdings  2015-06-16       1
3                      1023 Holdings  2016-06-15      -1
4   1210 Barton Springs Road Venture  2014-03-31       1
5   1210 Barton Springs Road Venture  2016-03-31      -1
6           1219 South Lamar Venture  2013-01-03       2
7           1219 South Lamar Venture  2014-01-03      -1
8           1219 South Lamar Venture  2015-01-03      -1
9                       16 Piggybank  2014-07-09       1
10                      16 Piggybank  2014-12-21       1
11                      16 Piggybank  2015-01-12       1
12                      16 Piggybank  2016-01-12      -2
13                      16 Piggybank  2016-07-20      -1
14                    1600 West 38th  2010-12-16       1
15                    1600 West 38th  2011-12-16      -1
16                            1715 G  2015-04-24       1
17                            1715 G  2015-06-27       1
18                            1715 G  2016-04-23      -1
19                            1715 G  2016-06-26      -1

In [124]:
cFrame['Cumulative'] = cFrame.groupby('Client')['Change'].apply(lambda x: x.cumsum())
# df['no_cumulative'] = df.groupby(['name'])['no'].apply(lambda x: x.cumsum())
cFrame.head(20)

                              Client        Date  Change  Cumulative
0                        1000 E. 6th  2014-08-20       1           1
1                        1000 E. 6th  2015-08-20      -1           0
2                      1023 Holdings  2015-06-16       1           1
3                      1023 Holdings  2016-06-15      -1           0
4   1210 Barton Springs Road Venture  2014-03-31       1           1
5   1210 Barton Springs Road Venture  2016-03-31      -1           0
6           1219 South Lamar Venture  2013-01-03       2           2
7           1219 South Lamar Venture  2014-01-03      -1           1
8           1219 South Lamar Venture  2015-01-03      -1           0
9                       16 Piggybank  2014-07-09       1           1
10                      16 Piggybank  2014-12-21       1           2
11                      16 Piggybank  2015-01-12       1           3
12                      16 Piggybank  2016-01-12      -2           1
13                      16 Piggybank  2016-07-20      -1           0
14                    1600 West 38th  2010-12-16       1           1
15                    1600 West 38th  2011-12-16      -1           0
16                            1715 G  2015-04-24       1           1
17                            1715 G  2015-06-27       1           2
18                            1715 G  2016-04-23      -1           1
19                            1715 G  2016-06-26      -1           0

In [125]:
croppedFrame = cFrame[cFrame.Date < lastDay]
# croppedFrame = cumFrame[cumFrame.Date < '2016-01-21']
print(croppedFrame.loc[cFrame['Client'] == 'AT&T'])
croppedFrame.tail()

    Client        Date  Change  Cumulative
131   AT&T  2013-06-18       1           1
132   AT&T  2013-08-06       4           5
133   AT&T  2013-08-07       2           7
134   AT&T  2013-08-13       1           8
135   AT&T  2013-10-07       2          10
136   AT&T  2013-10-08       1          11
137   AT&T  2014-08-06      -2           9
138   AT&T  2014-08-13      -1           8
139   AT&T  2015-03-06       1           9
140   AT&T  2015-08-20      -3           6
141   AT&T  2015-09-19       1           7
142   AT&T  2015-10-15      -1           6
143   AT&T  2016-03-04       1           7

                         Client        Date  Change  Cumulative
3267         Zydeco Development  2016-02-02      -1           3
3270  bella-mi Children's Store  2011-08-17       1           1
3271  bella-mi Children's Store  2012-08-16      -1           0
3272                  thinkEAST  2013-10-01       1           1
3273                  thinkEAST  2014-10-01      -1           0

In [126]:
croppedFrame.describe()

            Change   Cumulative
count  2337.000000  2337.000000
mean      0.471545     1.475396
std       1.135201     1.366621
min      -4.000000     0.000000
25%      -1.000000     1.000000
50%       1.000000     1.000000
75%       1.000000     2.000000
max       4.000000    11.000000

In [127]:
croppedFrame.to_csv('lobbyistByClient.csv', index = False)